name: Create/Delete Branch for Pull Request Workflow

on:
  workflow_call:
    inputs:
      project_id:
        description: A project ID.
        required: true
        type: string
      parent_branch:
        description: |
          A parameter to create a new branch. 
          The parent branch name or id or LSN or timestamp. 
          By default the primary branch is used.
        required: false
        type: string
      db:
        description: A parameter to create a new branch.
        required: false
        type: string
      role:
        description: A parameter to create a new branch.
        required: false
        type: string
    secrets:
      inherit:

jobs:
  neon_branch_management:
    name: Create/Delete Branch for Pull Request Job
    runs-on: ubuntu-latest
    steps:
      - name: Fetch integration data
        shell: bash
        run: |
          WORKFLOW=$(curl -H "accept: application/json" -H "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \ 
          https://console.neon.tech/api/v2/projects/${{ inputs.project_id} }}/applications/github \
          | jq -r ".workflows[] | select(.type == 'pr_branches')")
          echo $WORKFLOW
          echo "workflow_parent=$(echo $WORKFLOW | jq .template_values.parent)" >> $GITHUB_ENV
          echo "workflow_db=$(echo $WORKFLOW | jq .template_values.db)" >> $GITHUB_ENV
          echo "workflow_role=$(echo $WORKFLOW | jq .template_values.role)" >> $GITHUB_ENV

      - name: Create Neon Branch
        uses: neondatabase/create-branch-action@v5.0.0
        if: |
          ${{ github.event_name == 'pull_request' && (
          github.event.action == 'synchronize'
          || github.event.action == 'opened'
          || github.event.action == 'reopened')  }}
        with:
          project_id: ${{ inputs.project_id }}
          branch_name: preview/pr-${{ github.event.number }}
          parent: ${{ env.workflow_parent }}
          database: ${{ env.workflow_db }}
          username: ${{ env.workflow_role }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Reset Neon Branch
        uses: neondatabase/reset-branch-action@v1
        if: |
          ${{ contains(github.event.pull_request.labels.*.name, 'Reset Neon Branch') &&
          github.event_name == 'pull_request' &&
          (github.event.action == 'synchronize' ||
           github.event.action == 'opened' ||
           github.event.action == 'reopened') }}
        with:
          project_id: ${{ inputs.project_id }}
          parent: true
          branch: preview/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
        with:
          project_id: ${{ inputs.project_id }}
          branch: preview/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}